# Documentation


While we cannot possibly introduce every single TensorFlow function and class 
(and the information might become outdated quickly), 
the [API documentation](https://www.tensorflow.org/api_docs) and additional [tutorials](https://www.tensorflow.org/tutorials) and examples 
provide such documentation. 
This section provides some guidance for how to explore the TensorFlow API.


In [1]:
import tensorflow as tf

## Functions and Classes in a Module

In order to know which functions and classes can be called in a module,
we invoke the `dir` function. For instance, we can
(**query all properties in the module for generating random numbers**):


In [2]:
print(dir(tf.random))

['Algorithm', 'Generator', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_sys', 'all_candidate_sampler', 'categorical', 'create_rng_state', 'experimental', 'fixed_unigram_candidate_sampler', 'gamma', 'get_global_generator', 'learned_unigram_candidate_sampler', 'log_uniform_candidate_sampler', 'normal', 'poisson', 'set_global_generator', 'set_seed', 'shuffle', 'stateless_binomial', 'stateless_categorical', 'stateless_gamma', 'stateless_normal', 'stateless_parameterized_truncated_normal', 'stateless_poisson', 'stateless_truncated_normal', 'stateless_uniform', 'truncated_normal', 'uniform', 'uniform_candidate_sampler']


Generally, we can ignore functions that start and end with `__` (special objects in Python) 
or functions that start with a single `_`(usually internal functions). 
Based on the remaining function or attribute names, 
we might hazard a guess that this module offers 
various methods for generating random numbers, 
including sampling from the uniform distribution (`uniform`), 
normal distribution (`normal`), and multinomial distribution (`multinomial`).

## Specific Functions and Classes

For more specific instructions on how to use a given function or class,
we can invoke the  `help` function. As an example, let's
[**explore the usage instructions for tensors' `ones` function**].


In [3]:
help(tf.ones)

Help on function ones in module tensorflow.python.ops.array_ops:

ones(shape, dtype=tf.float32, name=None)
    Creates a tensor with all elements set to one (1).
    
    See also `tf.ones_like`, `tf.zeros`, `tf.fill`, `tf.eye`.
    
    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to one.
    
    >>> tf.ones([3, 4], tf.int32)
    <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
    array([[1, 1, 1, 1],
           [1, 1, 1, 1],
           [1, 1, 1, 1]], dtype=int32)>
    
    Args:
      shape: A `list` of integers, a `tuple` of integers, or
        a 1-D `Tensor` of type `int32`.
      dtype: Optional DType of an element in the resulting `Tensor`. Default is
        `tf.float32`.
      name: Optional string. A name for the operation.
    
    Returns:
      A `Tensor` with all elements set to one (1).



From the documentation, we can see that the `ones` function 
creates a new tensor with the specified shape 
and sets all the elements to the value of 1. 
Whenever possible, you should (**run a quick test**) 
to confirm your interpretation:


In [4]:
tf.ones(4)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

In the Jupyter notebook, we can use `?` to display the document in another
window. For example, `list?` will create content
that is almost identical to `help(list)`,
displaying it in a new browser window.
In addition, if we use two question marks, such as `list??`,
the Python code implementing the function will also be displayed.

The official documentation provides plenty of descriptions and examples that are beyond this book. 
Our emphasis lies on covering important use cases 
that will allow you to get started quickly with practical problems, 
rather than completeness of coverage. 
We also encourage you to study the source code of the libraries 
to see examples of high quality implementations for production code. 
By doing this you will become a better engineer 
in addition to becoming a better scientist.


[Discussions](https://discuss.d2l.ai/t/199)
